# Generated by Django 5.1.6 on 2025-03-04 23:55

import uuid
import valet_key_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValetKey',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255)),
                ('key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('expires_at', models.DateTimeField(default=valet_key_app.models.default_expiration)),
            ],
        ),
    ]
